DBPath = "./data"
LogPath = "./log"

[TLS]
ClientAuth = true #是否验证客户端证书
CipherSuit = ["TLS_AES_128_GCM_SHA256"]#密码套件
ClientCertCommandName="Painter" #客户端证书CN
DisableTLSLow = true #禁用1.1及以下
###############################################
#   TLS_AES_128_GCM_SHA256
# 	TLS_AES_256_GCM_SHA384
# 	TLS_CHACHA20_POLY1305_SHA256
# 	TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
# 	TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
# 	TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
# 	TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
# 	TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
# 	TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384

[IP]
out="192.168.3.1"
in="127.0.0.1"

[[PortMap]]
fromPort = 8080
toPort = 8081

[[Alert]]
url= ''
body=''

[[Alert]]
url= ''
body=''