// Code generated by "stringer -type CipherSuit"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256-49195]
	_ = x[TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384-49200]
	_ = x[TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384-49196]
	_ = x[TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256-52392]
	_ = x[TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256-52393]
	_ = x[TLS_AES_128_GCM_SHA256-4865]
	_ = x[TLS_AES_256_GCM_SHA384-4866]
	_ = x[TLS_CHACHA20_POLY1305_SHA256-4867]
}

const (
	_CipherSuit_name_0 = "TLS_AES_128_GCM_SHA256TLS_AES_256_GCM_SHA384TLS_CHACHA20_POLY1305_SHA256"
	_CipherSuit_name_1 = "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
	_CipherSuit_name_2 = "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
	_CipherSuit_name_3 = "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256"
)

var (
	_CipherSuit_index_0 = [...]uint8{0, 22, 44, 72}
	_CipherSuit_index_1 = [...]uint8{0, 39, 78}
	_CipherSuit_index_3 = [...]uint8{0, 43, 88}
)

func (i CipherSuit) String() string {
	switch {
	case 4865 <= i && i <= 4867:
		i -= 4865
		return _CipherSuit_name_0[_CipherSuit_index_0[i]:_CipherSuit_index_0[i+1]]
	case 49195 <= i && i <= 49196:
		i -= 49195
		return _CipherSuit_name_1[_CipherSuit_index_1[i]:_CipherSuit_index_1[i+1]]
	case i == 49200:
		return _CipherSuit_name_2
	case 52392 <= i && i <= 52393:
		i -= 52392
		return _CipherSuit_name_3[_CipherSuit_index_3[i]:_CipherSuit_index_3[i+1]]
	default:
		return "CipherSuit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
