// Code generated by "stringer -type CipherSuit -linecomment"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TLS_AES_128_GCM_SHA256-0]
}

const _CipherSuit_name = "TLS_AES_128_GCM_SHA256"

var _CipherSuit_index = [...]uint8{0, 22}

func (i CipherSuit) String() string {
	if i < 0 || i >= CipherSuit(len(_CipherSuit_index)-1) {
		return "CipherSuit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CipherSuit_name[_CipherSuit_index[i]:_CipherSuit_index[i+1]]
}
