// Code generated by "stringer -type LogLevel -linecomment"; DO NOT EDIT.

package logger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERROR-0]
	_ = x[NOTICE-1]
	_ = x[DEBUG-2]
}

const _LogLevel_name = "ERRORNOTICEDEBUG"

var _LogLevel_index = [...]uint8{0, 5, 11, 16}

func (i LogLevel) String() string {
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
