#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "golangci-lint run ./..."
golangci-lint run ./... --fix 
if [[ $? -ne 0 ]]; then
    exit 1;
fi
echo "go test ./..."
go test ./...
if [[ $? -ne 0 ]]; then
    exit 1;
fi
git add -u
